version: '2'

services:
    php:
        container_name: yin-middleware-php
        image: php:7.2-cli
        volumes:
            - .:/var/www
        command: /bin/bash -c "cd /var/www; php vendor/bin/phpunit"
